### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/lsd#1]
Hi @urrickhunt, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot!

Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by etrigan63** [comment]
Suggestion: the zip files you host on your repo should be moved here.

**Comment by urrickhunt** [comment]
Everything is moved & updated
