### ISSUE TITLE
Where is the theme?

### ISSUE THREAD

**Issue by notDavid** [dracula/lsd#3]
Hi there,

I just see a screenshot and readme, but no actual theme files to install... am i missing something? 😳

**Comment by notDavid** [comment]
fyi @luxonauta , not sure if any one looks at these issues, and you're the last person who committed... :-)

**Comment by luxonauta** [comment]
The maintainer of the repository is @urrickhunt; as I don't use the app and the theme itself, I can only help a little, but if it isn't being maintained, we have to take it down or notify it on the website 😔

**Comment by notDavid** [comment]
Thank you @luxonauta 

Probably just a mistake, as the file was recently still there... just noticed, the .yaml is [here](https://github.com/dracula/lsd/files/11355419/dracula.zip), found the url in this [commit](https://github.com/dracula/lsd/commit/0fe1dfe707377ac3fa882e016992c497ccc1bb64#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0R15) from 3 weeks ago.

**Comment by urrickhunt** [comment]
not sure what happened to the files but they are back. 

theme https://github.com/dracula/lsd/files/11517536/dracula.zip

config https://github.com/dracula/lsd/files/11517553/config.zip

the whole shebang https://github.com/dracula/lsd/archive/refs/heads/main.zip

thank you for letting us know 👍

**Comment by notDavid** [comment]
@urrickhunt The instructions at https://draculatheme.com/lsd don't work. The `.yaml` is not present in the .zip file.

The `.yaml` should also be in this repo anyway... so a history is available too.

**Comment by urrickhunt** [comment]
yes thank you again i think we got everything squared away my apologies ;)

**Comment by notDavid** [comment]
@urrickhunt No worries, thank you for creating and fixing! 🤗
